//! The canonical payloads: `FeatureRecord` and `PredictionRecord`.
//!
//! Generated by `prost` (`build.rs`) from `proto/cortex/contract/v1/feature_record.proto`
//! and `proto/cortex/contract/v1/prediction_record.proto` — the same `.proto`
//! definitions `protoc` generates into Python, so both languages agree on the
//! wire format byte for byte (in particular: `float` is unambiguously 32-bit
//! on both sides).

include!(concat!(env!("OUT_DIR"), "/cortex.contract.v1.rs"));
